// UI State
export const TOGGLE_HELP = "TOGGLE_HELP";
export const SET_ACTIVE_PERIOD = "SET_ACTIVE_PERIOD";
export const ADD_NEW_PERIOD = "ADD_NEW_PERIOD";
export const DELETE_PERIOD = "DELETE_PERIOD";
export const REORDER_PERIODS = "REORDER_PERIODS";
export const REPLACE_PROVENANCE = "REPLACE_PROVENANCE";
export const UPDATE_REFRESHED_TIME = "UPDATE_REFRESHED_TIME";
